### PR TITLE
Update to Ember 3.7

### PR DESCRIPTION
**Pull request by loganrosen**
Updating this addon to Ember 3.5, leveraging `ember-cli-update`.

### CODE REVIEW

**Comment by jelhan** [comment]
This looks good to me beside adding `package-lock.json` instead of `yarn.lock`. It would close #86 and #85.

**Comment by loganrosen** [comment]
Since Ember 3.7 is available now, I've updated this PR accordingly. I also switched to Yarn per @jelhan's comment.

**Comment by sandstrom** [comment]
@loganrosen Is there anything else you'd like to do with this PR, before we merge?

We'll make sure to add a changelog file where we can note that this is a breaking change. So that it'll be handled properly during the next version release.

**Comment by sandstrom** [comment]
friendly ping @loganrosen

**Comment by loganrosen** [comment]
@sandstrom Sorry for the delay! Just fixed a merge conflict against master (the Node version in `.travis.yml` was bumped to 8 in #84). This should be good to merge now, once Travis passes.

**Comment by sandstrom** [comment]
@loganrosen Great, thanks!

However, there seems to be a new error:

> Could not require 'ember-cli-build.js': Cannot find module 'broccoli-caching-writer'

**Comment by loganrosen** [comment]
@sandstrom Fixed the Travis failure by setting `useYarn` to `true` in the ember-try configuration. This time I made sure it passed. :smile: Good to merge now.

**Comment by sandstrom** [comment]
@loganrosen Awesome, thanks!! 🙏🏻

**Pull request merged**
