### PR TITLE
append frame-src config in test mode

### PR DESCRIPTION
**Pull request by chbonser**
Addresses https://github.com/rwjblue/ember-cli-content-security-policy/issues/151

Note this works in my case because my app has `frame-src` defined. From the failing tests it appears `appendSourceList` does not handle the case of a missing `frame-src` properly. Should `appendSourceList` get smarter or should this problem get solved via another approach?

### CODE REVIEW

**Comment by jelhan** [comment]
Thanks so a lot for working on this! Looks good to me. Haven't had the time to look at the failing test yet.
> From the failing tests it appears appendSourceList does not handle the case of a missing frame-src properly. Should appendSourceList get smarter or should this problem get solved via another approach?

It should already be that smart: https://github.com/rwjblue/ember-cli-content-security-policy/blob/43527edab59a68c8d747fede8cae4573d352baf2/lib/utils.js#L150-153

**Comment by rwjblue** [comment]
@chbonser - Have you had any time to debug the failure here?

**Comment by jelhan** [comment]
@rwjblue I fear it's related to the buggy ember-cli-addon-tests setup. I working on the side on a replacement for that one but haven't had the time to finish it yet.

**Comment by jelhan** [comment]
Closed and reopened to trigger another Travis run after test suite was refactored in #154.

**Comment by jelhan** [comment]
Getting a way more helpful error in CI now:

```
  1) e2e: provides test support
       includes frame-src required by testem
         includes frame-src required by testem in CSP delivered by meta tag:
     AssertionError: expected 'default-src \'none\'; script-src \'self\' \'nonce-abcdefg\' localhost:49741 0.0.0.0:49741; font-src \'self\'; connect-src \'self\' ws://localhost:49741 ws://0.0.0.0:49741; img-src \'self\'; style-src \'self\'; media-src \'self\'; frame-src \'none\' \'self\';' to include 'frame-src \'self\';'
      at Context.<anonymous> (node-tests/e2e/test-support-test.js:232:38)

  2) e2e: provides test support
       includes frame-src required by testem
         includes frame-src required by testem in CSP delivered by HTTP header:
     AssertionError: expected 'default-src \'none\'; script-src \'self\' \'nonce-abcdefg\' localhost:49741 0.0.0.0:49741; font-src \'self\'; connect-src \'self\' ws://localhost:49741 ws://0.0.0.0:49741; img-src \'self\'; style-src \'self\'; media-src \'self\'; frame-src \'none\' \'self\';' to include 'frame-src \'self\';'
      at Context.<anonymous> (node-tests/e2e/test-support-test.js:244:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

The test tries to find the string `frame-src 'self';`. But the CSP includes `frame-src 'none' 'self';'`.

This highlights a bug in `appendSourceList` utility. It does not remove an existing `'none'` keyword if applying an expression.

**Comment by jelhan** [comment]
Closing and reopening again after #156 has been merged. It should address the bug described in my last comment. Let's see.

**Comment by jelhan** [comment]
It's working. :clap: 

To avoid a regression I would prefer to have test coverage. There are already some tests coverage for `frame-src` in tests: https://github.com/rwjblue/ember-cli-content-security-policy/blob/8c4067ada6c8a0a93106d0a2e08acd5c490329bd/node-tests/e2e/test-support-test.js#L210-L246 An additional test should be added that it does not remove existing `frame-src` directive but appends to it.

**Comment by chbonser** [comment]
@jelhan I am buried in other things at the moment but I'll try to squeeze in time later this week to add the test you mentioned.

**Comment by jelhan** [comment]
Rebased and added a failing tests. Thanks a lot @chbonser for debugging and providing the original fix! I'm sorry that it took that long to get it in.

**Comment by chbonser** [comment]
Thanks @jelhan. Sorry I wasn't able to add the extra test coverage!

**Pull request merged**
